/**
 * PDF Generation Utility
 * Generates PDF reports for student health data
 */

export interface PDFReportOptions {
  title: string;
  studentName?: string;
  dateRange?: string;
  includeCharts?: boolean;
  sections?: string[];
}

/**
 * Generate PDF report using browser's print functionality
 * For production, consider using libraries like jsPDF, pdfmake, or react-pdf
 */
export const generatePDF = (options: PDFReportOptions) => {
  const {
    title,
    studentName,
    dateRange,
    includeCharts = false,
    sections = [],
  } = options;

  // Create a printable HTML content
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Popup blocked. Please allow popups to generate PDF.');
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @media print {
            @page {
              margin: 1cm;
              size: A4;
            }
            body {
              font-family: Arial, sans-serif;
              font-size: 12px;
              line-height: 1.6;
            }
            .header {
              border-bottom: 2px solid #000;
              padding-bottom: 10px;
              margin-bottom: 20px;
            }
            .header h1 {
              margin: 0;
              font-size: 24px;
            }
            .header .meta {
              color: #666;
              font-size: 11px;
              margin-top: 5px;
            }
            .section {
              margin-bottom: 20px;
              page-break-inside: avoid;
            }
            .section h2 {
              font-size: 16px;
              border-bottom: 1px solid #ccc;
              padding-bottom: 5px;
              margin-bottom: 10px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 10px 0;
            }
            table th, table td {
              border: 1px solid #ddd;
              padding: 8px;
              text-align: left;
            }
            table th {
              background-color: #f2f2f2;
              font-weight: bold;
            }
            .footer {
              margin-top: 30px;
              padding-top: 10px;
              border-top: 1px solid #ccc;
              font-size: 10px;
              color: #666;
              text-align: center;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <div class="meta">
            ${studentName ? `<strong>Student:</strong> ${studentName}<br>` : ''}
            ${dateRange ? `<strong>Date Range:</strong> ${dateRange}<br>` : ''}
            <strong>Generated:</strong> ${new Date().toLocaleString()}
          </div>
        </div>
        <div id="content">
          <!-- Content will be inserted here -->
        </div>
        <div class="footer">
          <p>Generated by School Health Information System (SHIS)</p>
          <p>Confidential - For authorized use only</p>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();

  // Wait for content to load, then trigger print
  setTimeout(() => {
    printWindow.print();
  }, 250);
};

/**
 * Generate PDF from HTML element
 */
export const generatePDFFromElement = (elementId: string, title: string) => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Popup blocked. Please allow popups to generate PDF.');
  }

  // Clone the element and its styles
  const clonedElement = element.cloneNode(true) as HTMLElement;
  
  // Get computed styles
  const styles = Array.from(document.styleSheets)
    .map(sheet => {
      try {
        return Array.from(sheet.cssRules)
          .map(rule => rule.cssText)
          .join('\n');
      } catch (e) {
        return '';
      }
    })
    .join('\n');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          ${styles}
          @media print {
            @page {
              margin: 1cm;
              size: A4;
            }
            body {
              font-family: Arial, sans-serif;
              font-size: 12px;
            }
          }
        </style>
      </head>
      <body>
        <div style="padding: 20px;">
          <h1 style="text-align: center; margin-bottom: 20px;">${title}</h1>
          ${clonedElement.outerHTML}
          <div style="margin-top: 30px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 10px; color: #666; text-align: center;">
            <p>Generated by School Health Information System (SHIS)</p>
            <p>Generated on: ${new Date().toLocaleString()}</p>
          </div>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();

  setTimeout(() => {
    printWindow.print();
  }, 250);
};

/**
 * Generate CSV export
 */
export const generateCSV = (data: any[], filename: string = 'report') => {
  if (!data || data.length === 0) {
    throw new Error('No data to export');
  }

  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','),
    ...data.map(row =>
      headers.map(header => {
        const value = row[header];
        return typeof value === 'string' && value.includes(',')
          ? `"${value}"`
          : value;
      }).join(',')
    ),
  ];

  const csvContent = csvRows.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Generate Excel export (CSV format, can be opened in Excel)
 */
export const generateExcel = (data: any[], filename: string = 'report') => {
  generateCSV(data, filename);
};


